# Generated by Django 5.0 on 2025-02-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLogApp', '0004_author_avatar_alter_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
